//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfHaberSite {
    
    
    public partial class Anasayfa {
        
        /// <summary>
        /// UC_MansetUzeriHaber control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ProfHaberSite.UserControl.UC_MansetUzeriHaber UC_MansetUzeriHaber;
    }
}
