//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaberAdmin.W_Anasayfa {
    
    
    public partial class Anasayfa {
        
        /// <summary>
        /// UC_MansetUzeriHaber control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HaberAdmin.W_WUC.UC_MansetUzeriHaber UC_MansetUzeriHaber;
        
        /// <summary>
        /// UC_MansetUzeriHaber1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HaberAdmin.W_WUC.UC_MansetUzeriHaber UC_MansetUzeriHaber1;
        
        /// <summary>
        /// UC_MansetAltiHaber control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HaberAdmin.W_WUC.UC_MansetAltiHaber UC_MansetAltiHaber;
        
        /// <summary>
        /// UC_SurmansetHaber control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HaberAdmin.W_WUC.UC_SurmansetHaber UC_SurmansetHaber;
        
        /// <summary>
        /// UC_AnasayfaKategoriler control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HaberAdmin.W_WUC.UC_AnasayfaKategoriler UC_AnasayfaKategoriler;
    }
}
